name: Deploy Vue.js to VPS

on:
  push:
    branches:
      - main # ou master, selon ton repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # ou la version que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            rm -rf /var/www/vue-app/*
            cp -r ./dist/* /var/www/vue-app/
            sudo chown -R www-data:www-data /var/www/vue-app
            sudo systemctl restart nginx
